django_blog/blog/urls.py
from django.urls import path
from .views import (
    PostListView, 
    PostDetailView,
    PostCreateView,
    PostUpdateView, 
    PostDeleteView
)
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),

    path('rate-post/', views.post_rate, name='post-rate'),
    path('fav-post/', views.post_fav, name='post-fav'),

    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='blog-about'),
]

django_blog/django_blog/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),

    path('', include('blog.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', user_views.MyLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', user_views.MyLogoutView.as_view(template_name='users/logout.html'), name='logout'),
    
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    
    path('profile/settings/', user_views.profile, name='profile-settings'),
    path('user/<slug>', user_views.UserDetailView.as_view(template_name='users/profile.html'), name='user-profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_blog/blog/models.py
from email.policy import default
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from tinymce import models as tinymce_models

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = tinymce_models.HTMLField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})


class PostRating(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    action = models.CharField(max_length=20)

    def get_rating(self):
        likes = PostRating.objects.filter(post=self.post, action='like').count()
        dislikes = PostRating.objects.filter(post=self.post, action='dislike').count()
        return likes - dislikes

    def __str__(self):
        return f'{self.user} {self.action} {self.post}'

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'post'], name='unique_user_post_combination')
        ]


class PostFav(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fav = models.BooleanField()

    def __str__(self):
        return f'{self.user} fav "{self.post}"'

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'post'], name='unique_user_post_combination_fav')
        ]


class PostComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=250)
    date = models.DateTimeField(auto_now_add=True)
    score = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.user} comment "{self.post}"'


class PostCommentRating(models.Model):
    comment = models.ForeignKey(PostComment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    action = models.CharField(max_length=20)

    def get_rating(self):
        likes = PostCommentRating.objects.filter(comment=self.comment, action='like').count()
        dislikes = PostCommentRating.objects.filter(comment=self.comment, action='dislike').count()
        return likes - dislikes

    def __str__(self):
        return f'{self.user} {self.action} comment-id: {self.comment.id}'

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'comment'], name='unique_user_comment_combination')
        ]

django_blog/blog/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit
from tinymce.widgets import TinyMCE
from django import forms
from .models import PostComment, Post


class CommentCreateForm(forms.ModelForm):
    content = forms.CharField(max_length=250)

    def __init__(self, *args, **kwargs):
        super(CommentCreateForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.template = 'blog/form_template_comment.html'
        self.helper.layout = Layout(
            Field('content', template='blog/field_comment.html'),
            Submit('submit', 'Send')
        )


    class Meta:
        model = PostComment
        fields = ['content']

class PostCreateForm(forms.ModelForm):
    content = forms.CharField(widget=TinyMCE(attrs={'cols': 80,'rows': 30,}))

    class Meta:
        model = Post
        fields = ['title', 'content']

django_blog/blog/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, View
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .models import Post, PostCommentRating, PostRating, PostFav, PostComment
from .forms import CommentCreateForm, PostCreateForm
import json



def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html' # <app>/<model>_<viewtype>.html as default
    context_object_name = 'posts' # <model>_list as default
    paginate_by = 5

    def get_ordering(self):
        ordering = [self.request.GET.get('order', '-date_posted')]
        return ordering

    def get_context_data(self, **kwargs):
        
        context = super(PostListView, self).get_context_data(**kwargs)

        return context


@login_required
def post_rate(request):
    if request.method == 'POST':
        user = request.user
        json_data = json.loads(request.body)
        action = json_data['action']
        post = json_data['post_id']
        post = Post.objects.get(pk=post)
        post_r = PostRating.objects.update_or_create(user=user, post=post, defaults={'action': action})

        response = HttpResponse(request, content_type='text/plain', headers={'content': 'Yay'})

        user_like_list = PostRating.objects.filter(user=user, action='like').values_list('post', flat=True)
        response.set_cookie('user_like_list', list(user_like_list))

        user_dislike_list = PostRating.objects.filter(user=user, action='dislike').values_list('post', flat=True)
        response.set_cookie('user_dislike_list', list(user_dislike_list))

        response.headers['score'] = post_r[0].get_rating()

        return response


@login_required
def post_fav(request):
    if request.method == 'POST':
        user = request.user

        json_data = json.loads(request.body)
        if json_data['fav'] == 'True':
            fav = 1
        else: fav = 0

        post = json_data['post_id']
        post = Post.objects.get(pk=post)

        PostFav.objects.update_or_create(user=user, post=post, defaults={'fav': fav})

        user_fav_list = PostFav.objects.filter(user=user, fav=1).values_list('post', flat=True)

        response = HttpResponse(request, content_type='text/plain', headers={'content': 'Yay'})
        response.set_cookie('user_fav_list', list(user_fav_list))

        return response



class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html' # <app>/<model>_<viewtype>.html as default
    context_object_name = 'posts' # <model>_list as default
    ordering = ['-date_posted']
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            try:
                comment_list = PostCommentRating.objects.filter(comment__post=self.get_object(), user=self.request.user)
            except:
                comment_list = None

            context.update({
                'form': CommentCreateForm(),
                'comment_user_vote_list': comment_list
            })

        ordering = self.request.GET.get('order', '-date')

        try:
            comments = PostComment.objects.filter(post=self.get_object()).order_by(ordering)
            comments_count = comments.count()
            paginator = Paginator(comments, 7)
            page_number = self.request.GET.get('page')
            page_comments = paginator.get_page(page_number)

        except:
            page_comments = None
            comments_count = None

        context.update({
            'post_comments': page_comments,
            'comments_count': comments_count
        })
        return context

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            comment_form = CommentCreateForm(request.POST)
            if comment_form.is_valid():
                self.object = self.get_object()
                comment_form.instance.user = request.user
                comment_form.instance.post = self.get_object()
                comment_form.save()
                return self.render_to_response(context=self.get_context_data())
            json_data = json.loads(request.body)
            if json_data['comment-id'] and json_data['comment-action']:
                comment = PostComment.objects.get(id=json_data['comment-id'])
                action = json_data['comment-action']
                
                comment_object = PostCommentRating.objects.update_or_create(comment=comment, user=request.user, defaults={'action': action})

                return HttpResponse(request, content_type='text/plain', headers={'comment-score': comment_object[0].get_rating()})


class PostCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Post
    form_class = PostCreateForm
    success_message = "Post was published"
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = Post
    fields = ['title', 'content']
    success_message = 'Post was updated'
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, DeleteView):
    model = Post
    success_message = 'Post was deleted successfully'
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})

django_blog/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}

    <h1>About Page</h1>

{% endblock content %}

django_blog/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="usr-auth-check" content="{{ user.is_authenticated }}" >
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    {% block head %}{% endblock head %}
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
    {% if title %}
        <title>Django Blog - {{ title }}</title>
    {% else %}
        <title>Django Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel sticky-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">Django Blog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog-home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog-about' %}">About</a>
                </li>
              </ul>
              <!-- Navbar Right Side -->
              <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'post-create' %}">New Post</a>
                </li>
                <li class="nav-item dropdown">
                    <img class="rounded-circle border comment-img" src="{{ user.profile.image.url }}" alt="">
                    <a class="nav-link nav-link-profile text-decoration-none dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ user.username }}</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="{% url 'user-profile' user.username %}">Your profile</a></li>
                      <li><a class="dropdown-item" href="{% url 'profile-settings' %}">Settings</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
    </header>
    <main role="main" class="container mt-2">
        <div class="row">
          <div class="col-md-8">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
          </div>
          <div class="col-md-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  {% block sidebar %}{% endblock sidebar %}
                  <li class="list-group-item list-group-item-light"><span class="placeholder col-9 bg-primary"></span></li>
                  <li class="list-group-item list-group-item-light"><span class="placeholder col-5 bg-success"></span></li>
                  <li class="list-group-item list-group-item-light"><span class="placeholder col-12 bg-warning"></span></li>
                  <li class="list-group-item list-group-item-light"><span class="placeholder col-7 bg-danger"></span></li>
                </ul>
              </p>
            </div>
          </div>
        </div>
    </main>
    <script src="{% static 'blog/main.js' %}"></script>
</body>
</html>

django_blog/blog/templates/blog/field_comment.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}

    <div id="div_{{ field.auto_id }}" class="form-floating">
                {% if field_class %}<div class="{{ field_class }}">{% endif %}
                    {% if field.errors %}
                        {% crispy_field field 'class' 'form-control comment-input is-invalid' %}
                    {% else %}
                        {% crispy_field field 'class' 'form-control comment-input' %}
                    {% endif %}
                    {% if not field|is_file %}
                        {% include 'bootstrap5/layout/help_text_and_errors.html' %}
                    {% endif %}
                {% if field_class %}</div>{% endif %}
                <label for="{{ field.id_for_label }}" class="form-label{% if field.field.required %} requiredField{% endif %}">
                    Your comment
                </label>
    </div>

{% endif %}

django_blog/blog/templates/blog/form_template_comment.html
{% load crispy_forms_utils %}

{% specialspaceless %}
{% if form_tag %}<form {{ flat_attrs }} method="{{ form_method|upper }}" class="d-grid gap-2 mt-2" >{% endif %}
    {% if form_method|lower == 'post' and not disable_csrf %}
        {% csrf_token %}
    {% endif %}

    {% include "bootstrap5/display_form.html" %}

    {% include "bootstrap5/inputs.html" %}

{% if form_tag %}</form>{% endif %}
{% endspecialspaceless %}

django_blog/blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% load string_to_int_list %}
{% block content %}
    {% for post in posts %}
        <article class="media card mb-4 shadow">
            <div class="d-flex flex-column card-header">
                <div class="d-flex flex-row">
                    <div class="d-flex flex-column position-relative me-auto">
                        <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}" alt="">
                        <a class="text-decoration-none stretched-link text-center" href="{% url 'user-profile' post.author.username %}">{{ post.author }}</a>
                    </div>
                    <div class="d-flex flex-column justify-content-center">
                        <div>
                            <input type="checkbox" class="btn-check fav" id="btn-fav-{{ post.id }}" post_id="{{ post.id }}" autocomplete="off" {% if request.COOKIES.user_fav_list and post.id in request.COOKIES.user_fav_list|string_to_int_list %}checked{% endif %}>
                            <label class="btn btn-warning fav me-2" for="btn-fav-{{ post.id }}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                                  </svg>
                            </label>
                            <div class="btn-group">
                                <input type="radio" class="btn-check" name="post-option{{ post.id }}" id="like{{ post.id }}" autocomplete="off"
                                {% if user.is_authenticated and post.id in request.COOKIES.user_like_list|string_to_int_list %}
                                    checked
                                {% endif %}>
                                <label class="btn btn-outline-success btn-outline-success-inverted btn-padding-0 vote" action="like" post_id="{{ post.id }}" for="like{{ post.id }}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="2rem" height="2rem" fill="currentColor" class="bi bi-arrow-up-square-fill" viewBox="0 0 16 16">
                                        <path d="M2 16a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2zm6.5-4.5V5.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 5.707V11.5a.5.5 0 0 0 1 0z"/>
                                    </svg>
                                </label>
                                {% if post.postrating_set.first %}
                                    <span class="btn btn-secondary btn-padding score lh-lg fw-bold disabled 
                                    {% if post.score > 0 %}text-success 
                                    {% elif post.score < 0 %}text-danger
                                    {% else %}text-muted
                                    {% endif %}" id="{{ post.id }}_score">{{ post.score }}</span>
                                {% else %}
                                    <span class="btn btn-secondary btn-padding score lh-lg fw-bold disabled text-muted" id="{{ post.id }}_score">0</span>
                                {% endif %}
                                <input type="radio" class="btn-check" name="post-option{{ post.id }}" id="dislike{{ post.id }}" autocomplete="off"
                                {% if user.is_authenticated and post.id in request.COOKIES.user_dislike_list|string_to_int_list %}
                                    checked
                                {% endif %}>
                                <label class="btn btn-outline-danger btn-outline-danger-inverted btn-padding-0 vote" action="dislike" post_id="{{ post.id }}" for="dislike{{ post.id }}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="2rem" height="2rem" fill="currentColor" class="bi bi-arrow-down-square-fill bi-arrow" viewBox="0 0 16 16">
                                        <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L7.5 10.293V4.5a.5.5 0 0 1 1 0z"></path>
                                    </svg>
                                </label>
                            </div>
                        </div>
                        <div class="text-end">
                            <small class="text-muted">{{ post.date_posted|date:"j F, Y" }}</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <h2><a class="article-title text-decoration-none" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
                <div class="article-content overflow-auto">
                    {% if post.content|safe|length > 550 %}
                        {{ post.content|safe|slice:":551" }} &ensp;...
                        <p>
                            <a class="btn btn-secondary btn-sm" href="{% url 'post-detail' post.id %}">Full post</a>
                        </p>
                    {% else %}
                        {{ post.content|safe }}
                    {% endif %}
                </div>
            </div>
            <div class="card-footer d-flex">
                <div class="position-relative d-inline-flex align-items-center me-auto">
                    <a class="stretched-link" href="{% url 'post-detail' post.id %}"></a>
                    <span class="me-2">Comments: {{ post.postcomment_set.count }}</span>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
                        <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"/>
                    </svg>
                </div>
            </div>
        </article>
    {% endfor %}
    {% if is_paginated %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="#" value="1">First</a></li>
            <li class="page-item">
                <a class="page-link" href="#" value="{{ page_obj.previous_page_number }}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
            <li class="page-item active"><a class="page-link" href="#" value="{{ num }}">{{ num }}</a></li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
            <li class="page-item"><a class="page-link" href="#" value="{{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="#" value="{{ page_obj.next_page_number }}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            <li class="page-item"><a class="page-link" href="#" value="{{ page_obj.paginator.num_pages }}">Last</a></li>
        {% endif %}
        </ul>
    </nav>
    {% endif %}
{% endblock content %}
{% block sidebar %}
    <li class="list-group-item list-group-item-light">
        <select class="form-select btn btn-secondary" id="selectOrdering" aria-label="Ordering select">
            <option selected>Sorting</option>
            <option value="-date_posted">New first</option>
            <option value="date_posted">Old first</option>
            <option value="score">Score asc</option>
            <option value="-score">Score desc</option>
          </select>
    </li>
{% endblock sidebar %}

django_blog/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="content-section">
    <form class="m-2" method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete Post</legend>
            <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

django_blog/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block head %}
    {{ form.media }}
{% endblock head %}
{% block content %}
<div class="content-section">
    <form class="m-2" method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">New Post</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Post</button>
        </div>
    </form>
</div>
{% endblock content %}